In [1]:
import numpy as np
import pandas as pd
import requests

# 1 - upload the data frames
locations_df = pd.read_excel("kalpi_adresses.xlsx")
results_df = pd.read_csv("kalpi_results.csv")
precincts_df = pd.read_csv("precincts.csv")

In [ ]:
# import requests

# def geocode_israel(address, city):
#     """
#     Geocode an Israeli address using ArcGIS.
#     Input:
#         address (str): street + house number
#         city (str): city/town/village name
#     Output:
#         (lat, lon) tuple or (None, None) if not found
#     """

#     # Combine into one correct Hebrew search string
#     full_address = f"{address}, {city}, ישראל"

#     url = "https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates"
#     params = {
#         "f": "json",
#         "SingleLine": full_address,
#         "countryCode": "ISR",
#         "outFields": "Match_addr"
#     }

#     response = requests.get(url, params=params)
#     data = response.json()

#     if data.get("candidates"):
#         top = data["candidates"][0]
#         lat = top["location"]["y"]
#         lon = top["location"]["x"]
#         return lat, lon

#     return None, None

In [2]:
results_df.head()

,yisuv name,yisuv id,קלפי,rikuz,מצביעים,כשרים,אמת,אצ,ב,ג,...,צ,ץ2,ק,קי,קך,קנ,קץ,רז,שס,ת
0,אבו גווייעד שבט,967.0,3.1,1.0,173.0,169.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
1,אבו גווייעד שבט,967.0,3.2,1.0,96.0,95.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,אבו גווייעד שבט,967.0,3.3,1.0,169.0,168.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
3,אבו גווייעד שבט,967.0,3.4,1.0,111.0,108.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
4,אבו גוש,472.0,1.1,5.0,360.0,353.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:

# # group locations together 
# locations_grouped_df = (
#     locations_df.groupby(["yisuv id", "rikuz"])
#     .agg({
#         "address": lambda x: list(set(x)),
#         "yisuv name": lambda x: list(set(x)),
#     })
#     .reset_index()
# )

# # verify address consistency
# def verify_single(lst, field):
#     if len(lst) != 1:
#         raise ValueError(f"Inconsistent {field}: {lst}")
#     return lst[0]

# locations_grouped_df["address"] = locations_grouped_df["address"].apply(
#     lambda lst: verify_single(lst, "address")
# )

# locations_grouped_df["yisuv name"] = locations_grouped_df["yisuv name"].apply(
#     lambda lst: verify_single(lst, "location_name")
# )

# locations_grouped_df["lat"] = 0.0
# locations_grouped_df["lon"] = 0.0

In [ ]:
right_block = ['מחל', 'שס', 'ג', 'ט', 'ב']
left_block = ['אמת', 'מרצ', 'כן', 'פה', 'ל']
arab_block = ['ד', 'ום', 'עם']

results_df["left_votes"] = results_df[left_block].sum(axis=1)
results_df["right_votes"] = results_df[right_block].sum(axis=1)
results_df["arab_votes"] = results_df[arab_block].sum(axis=1)

# group results together 
results_grouped_df = (
    results_df.groupby(["yisuv id", "rikuz"])
    .agg(
        left=("left_votes", "sum"),
        right=("right_votes", "sum"),
        arab=("arab_votes", "sum")
    )
    .reset_index()
)

#  group locations together 
locations_grouped_df = (
    locations_df.groupby(["yisuv id", "rikuz"])
    .agg(
        population=("eligible", "sum"),
    )
    .reset_index()
)


print(results_grouped_df.head())
print(locations_grouped_df.head())

   yisuv id  rikuz   left  right  arab
0       7.0    1.0  128.0  245.0   0.0
1      10.0    1.0    7.0  260.0   0.0
2      11.0    1.0  177.0  118.0   0.0
3      13.0    1.0  339.0   55.0   5.0
4      15.0    1.0   12.0  230.0   0.0